# Generated by Django 5.2.5 on 2025-08-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('summary_json', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
