# Generated by Django 4.2.23 on 2025-08-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='summary_json',
        ),
    ]
