# Generated by Django 4.2.23 on 2025-08-29 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0002_alter_contact_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contactd',
        ),
    ]
