# Generated by Django 4.2.23 on 2025-08-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cq', '0003_rename_contact_contactd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='query',
            new_name='queryd',
        ),
    ]
